# Generated by Django 3.0 on 2020-02-21 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 11, 12, 21, 131489), verbose_name='Published: '),
        ),
    ]
