# Generated by Django 3.0 on 2020-02-21 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200221_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_venue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 13, 54, 32, 574943), verbose_name='Published: '),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_title',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
