# Generated by Django 3.0 on 2020-02-21 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200221_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 15, 18, 59, 441800), verbose_name='Published: '),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
