# Generated by Django 3.0 on 2020-02-21 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200221_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 15, 27, 11, 694061), verbose_name='Published: '),
        ),
    ]
