# Generated by Django 3.0 on 2020-03-10 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200221_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 21, 48, 37, 784492), verbose_name='Published: '),
        ),
    ]
